# Generated by Django 4.0.3 on 2022-03-17 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_shop', to=settings.AUTH_USER_MODEL),
        ),
    ]
