# Generated by Django 4.0.3 on 2022-03-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(default='kanpur', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='state',
            field=models.CharField(default='uttar pradesh', max_length=64),
            preserve_default=False,
        ),
    ]
