# Generated by Django 4.0.3 on 2022-03-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0003_shop_city_shop_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='sales',
            field=models.IntegerField(default=0),
        ),
    ]
