# Generated by Django 4.0.3 on 2022-03-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0004_shop_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
