# Generated by Django 4.0.3 on 2022-03-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0005_orderhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='ipAddress',
        ),
    ]
