# Generated by Django 4.0.3 on 2022-03-17 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publisher', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shopId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_product', to='publisher.shop'),
        ),
        migrations.AddField(
            model_name='product',
            name='tagId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.tag'),
        ),
    ]
