# Generated by Django 4.0.3 on 2022-03-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shopId',
            new_name='shopid',
        ),
    ]
