# Generated by Django 4.0.3 on 2022-03-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_shopid_product_shopid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shopid',
            new_name='shopId',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tagId',
        ),
    ]
