# Generated by Django 4.0.3 on 2022-03-18 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_shopid_product_shopid_remove_product_tagid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tagId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.tag'),
        ),
    ]
