# Generated by Django 4.0.3 on 2022-03-31 15:58

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_feedbackvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='/default.jpg', upload_to=product.models.setImageName),
            preserve_default=False,
        ),
    ]
