# Generated by Django 4.0.3 on 2022-04-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_photo_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='alternate',
            field=models.CharField(default='k3b4k1b4', max_length=255, null=True),
        ),
    ]
