# Generated by Django 4.0.3 on 2022-04-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_images_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='path',
            field=models.ImageField(default='/default.jpg', upload_to=''),
        ),
    ]
