# Generated by Django 4.0.3 on 2022-04-02 09:44

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to=product.models.setImageName)),
            ],
        ),
    ]
