# Generated by Django 4.0.3 on 2022-04-01 17:00

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localuser',
            name='profilePhoto',
            field=models.ImageField(default='F:/github/e-commerce/e-commerce-backend/media/profile-images/photos/default.jpg', null=True, upload_to=users.models.setImageName),
        ),
    ]
