# Generated by Django 4.0.3 on 2022-03-17 21:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressId', models.AutoField(primary_key=True, serialize=False)),
                ('AddressValueError', models.CharField(default='-', max_length=255)),
                ('pincode', models.CharField(max_length=6)),
                ('registrationDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackId', models.AutoField(primary_key=True, serialize=False)),
                ('starValue', models.IntegerField()),
                ('timeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('review', models.TextField(max_length=600)),
                ('ipAddress', models.GenericIPAddressField(default='127.0.0.1')),
                ('browser', models.CharField(default='localhost:chrome', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('transactionId', models.CharField(max_length=255)),
                ('orderPlaceTime', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('orderDispatchTime', models.DateTimeField(null=True)),
                ('orderShippedTime', models.DateTimeField(null=True)),
                ('orderDeliveryTime', models.DateTimeField(null=True)),
                ('paymentTime', models.DateTimeField(null=True)),
                ('status', models.CharField(default='placed', max_length=10)),
                ('pincode', models.IntegerField()),
                ('paymentOption', models.CharField(max_length=16)),
                ('paymentDone', models.BooleanField(default=False)),
                ('paymentGateway', models.CharField(max_length=64)),
                ('ipAddress', models.GenericIPAddressField(default='127.0.0.1')),
                ('browser', models.CharField(default='localhost:chrome', max_length=255)),
                ('addressId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.address')),
            ],
        ),
    ]
