# Generated by Django 4.0.3 on 2022-03-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_feedback_shopid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='AddressValueError',
            new_name='address',
        ),
    ]
