# Generated by Django 4.0.3 on 2022-03-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_address_city_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='heading',
            field=models.CharField(default='', max_length=64),
        ),
    ]
